name: sonify
description: Music streaming app
publish_to: 'none'

version: 1.8.0+17

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # UI
  flutter_svg: ^2.0.17
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  fading_edge_scrollview: ^4.1.1
  toastification: ^3.0.2

  # network
  youtube_explode_dart: ^2.3.6
  http: ^1.3.0
  dio: ^5.7.0
  connectivity_plus: ^6.1.2

  # data
  json_serializable: ^6.7.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.4.0

  # firebase
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.2.0

  # file
  # uri_to_file: ^1.0.0
  path_provider: ^2.1.5

  # DI
  injectable: ^2.3.2
  get_it: ^8.0.3

  # state
  flutter_bloc: ^9.1.0

  # auth
  google_sign_in: ^6.2.1

  # audio
  audio_session: ^0.1.23
  audio_service: ^0.18.16
  just_audio: ^0.9.43
  # on_audio_query: ^2.9.0

  # util
  logging: ^1.3.0
  timeago: ^3.7.0
  video_player: ^2.9.2
  flutter_hooks: ^0.21.2
  synchronized: ^3.3.0
  uuid: ^4.5.1
  permission_handler: ^11.4.0
  flutter_dotenv: ^5.2.1
  collection: ^1.18.0
  url_launcher: ^6.3.1
  app_links: ^6.3.3
  path: ^1.9.0

  sonify_storage:
    path: ./packages/sonify_storage
  sonify_client:
    path: ./packages/sonify_client
  sonify_video_player:
    path: ./packages/sonify_video_player
  domain_data:
    path: ./packages/domain_data
  flappy_plane:
    path: ./packages/flappy_plane

  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  flutter_gen: ^5.4.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  storage_view: ^0.1.0-dev.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - env/
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/images/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/logo.png'
  image_path_android: 'assets/logo/logo_transparent_bg.png'
  min_sdk_android: 21

  remove_alpha_ios: true
  adaptive_icon_background: '#ffffffff'

flutter_native_splash:
  color: '#000000'
  image: assets/logo/logo_transparent_bg.png

  android_12:
    image: assets/logo/logo_transparent_bg.png
    color: '#000000'
    icon_background_color: '#000000'
