name: sonify
description: Music streaming app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1

  # UI
  flutter_svg: ^2.0.8

  # Network
  youtube_explode_dart: ^2.0.2
  http: ^1.1.0

  # Data
  json_serializable: ^6.7.0

  # DI
  injectable: ^2.3.2
  get_it: ^7.6.4

  # State
  flutter_bloc: ^8.1.3

  # Util
  logging: ^1.2.0

  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  flutter_gen: ^5.3.2

flutter:
  uses-material-design: true

  # generate: true

  assets:
    - .env.development
    - .env.production
    - .env.local
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
