name: sonify
description: Music streaming app

publish_to: 'none'

version: 0.2.1+3

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1

  # UI
  flutter_svg: ^2.0.10+1
  flip_card: ^0.6.0
  sliding_up_panel: ^2.0.0+1
  palette_generator: ^0.3.3+3
  marquee: ^2.2.3
  audio_video_progress_bar: ^2.0.2
  cached_network_image: ^3.3.1
  kartal: ^2.0.0

  # Network
  youtube_explode_dart: ^2.1.0
  http: ^1.2.1
  dio: ^5.4.1

  # Data
  json_serializable: ^6.7.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # DI
  injectable: ^2.3.2
  get_it: ^7.6.7

  # State
  flutter_bloc: ^8.1.4

  # auth
  google_sign_in: ^6.2.1

  # audio
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  audiotagger: ^2.2.1
  just_audio: ^0.9.30

  # Util
  logging: ^1.2.0
  timeago: ^3.6.1
  video_player: ^2.8.2
  flutter_hooks: ^0.20.5
  path_provider: ^2.1.2
  synchronized: ^3.1.0+1
  uuid: ^4.3.3
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.1.0
  collection: ^1.18.0
  url_launcher: ^6.2.5
  app_links: ^4.0.1

  sonify_storage:
    path: ./packages/sonify_storage
  sonify_client:
    path: ./packages/sonify_client
  sonify_video_player:
    path: ./packages/sonify_video_player

  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  flutter_gen: ^5.4.0

flutter:
  uses-material-design: true

  # generate: true

  assets:
    - env/
    - assets/
    - assets/icons/
    - assets/logo/
