name: domain_data
description: domain models and data for sonify
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.1.4

dependencies:
  freezed_annotation: ^2.4.1
  logging: ^1.2.0
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2

  sonify_storage:
    path: ../sonify_storage
  sonify_client:
    path: ../sonify_client

  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities

dev_dependencies:
  flutter_lints: ^3.0.1
  freezed: ^2.3.5
  build_runner: ^2.4.5
