import 'package:domain_data/domain_data.dart';

final dummyAudioNames = [
  '"""Red Swan"" (Attack on Titan anime theme) - 進撃の巨人 Official Lyric Video YOSHIKI feat. HYDE"',
  '505 - Arctic Monkeys',
  'ABBA Lay All Your Love On Me',
  'Ace of Base - Happy Nation (Lyrics)',
  'Aerosmith - Dream On (Official Audio)',
  '"Alok, Martin Jensen, Jason Derulo - Don\'t Cry For Me (Lyrics)"',
  'Alt J - Left Hand Free',
  'Amy Macdonald - This Is The Life (Lyrics)',
  'Amy Winehouse - Back To Black (Lyrics)',
  '"Antonio Vivaldi  - The Four Seasons - Violin Concerto in F Minor, RV 297, “Winter”, I. Al. Non Molto"',
  'Arcane Intro - Enemy (Extended No Rap) | Cinematic',
  'Arctic Monkeys - Do I Wanna Know? (Official Video)',
  'Are You With Me - Lost Frequencies [Lyrics]',
  "Attack on Titan - 'Call Your Name' with Lyrics",
  "Attack on Titan OST - Before Lights Out『Erwin's Charge Theme』",
  'Attack on Titan OST — Bauklötze [Eng Sub]',
  'Ausländer - Rammstein Lyrics',
  'Barns Courtney - Glitter & Gold (Lyrics)',
  'Bastille - Pompeii (Lyrics)',
  'bbno\$ - edamame (Lyrics) ft. Rich Brian',
  'Billy Joel - Piano Man (Audio)',
  '"Billy Joel - Vienna (Lyrics) | slow down youre doing fine, you can\'t be everything you wanna be"',
  "Billy Joel - We Didn't Start the Fire (Audio)",
  'Black Sabbath - Paranoid (Official Audio)',
  'Bonnie Tyler - Holding out for a hero (Lyrics on screen)',
  'Burning heart Survivor lyrics',
  'Cage The Elephant - Come A Little Closer (TikTok Remix) [Lyrics]',
  'Cailin Russo and Chrissy Costanza - Phoenix',
  'Central Cee x Dave - Sprinter (Lyrics)',
  'Centuries - Fall Out Boy (Lyrics)',
  '"Cheriimoya, Sierra Kidd - Living Life, In The Night【Slowed + reverb】"',
  "Coolio - Gangsta's Paradise [NFS Edit - JustResurrected Remake]",
  'Courtesy Call - Thousand Foot Krutch (Lyrics)',
  'CYGO - Panda E',
  'David Bowie - Life On Mars? (2021 Remaster)',
  'David Bowie - Rebel Rebel - Lyrics',
  'David Guetta - Dangerous',
  'Davy Jones [Lyrics]',
  'Daydream',
  '"DREAMERS, American Teeth, Wes Period - Still Not Dead (Visualizer Video)"',
  'Electric Light Orchestra - Mr  Blue Sky (Lyrics)',
  'Elton John - Goodbye Yellow Brick Road (lyrics)',
  'Elton John - Rocket Man (Lyrics)',
  'Eminem - Mockingbird (Lyrics)',
  'Ethan Bortnick - engravings (Lyrics)',
  'Europe -The Final Countdown (lyrics)',
  'Eurythmics - Sweet Dreams [Lyrics]',
  'Fairytale - Alexander Rybak ( slowed & remix ) tiktok remix { Lyrics }',
  'Fall Out Boy - Light Em Up ',
  'Fall Out Boy - Phoenix',
  "FERDA - I just wanna chill 'n twist the lot. [ TikTok ]",
  'Freaks - Surf Curse (Lyrics) 🎵',
  'French Montana ‒ Unforgettable (Lyrics) 🎤 ft. Swae Lee',
  'Fun.: We Are Young ft. Janelle Monáe [OFFICIAL VIDEO]',
  'Ghost - Mary On A Cross (Lyrics)',
  "Grand Commander - fuck you i'm going underground",
  'Green Day - Boulevard of Broken Dreams (Lyrics)',
  'Green Day - Holiday (Audio)',
  "Guns N' Roses - This I Love Lyrics",
  'House of Memories (Slowed & Reverb) Lyrics...',
  'Hozier - Take Me To Church Lyric Video',
  'Imagine Dragons - Believer',
  'Imagine Dragons - Believer (Romy Wave Cover) [NSG ',
  'Imagine Dragons - Bones (Official Lyric Video)',
  'Imagine Dragons - Mouth of the River',
  'Imagine Dragons - Natural',
  'Imagine Dragons - Nothing Left To Say (Art Film)',
  'Imagine Dragons - Radioactive',
  'Imagine Dragons - Sharks (Official Lyric Video)',
  'Imagine Dragons - Whatever It Takes (Lyrics / Lyri',
  'Imagine Dragons - Wrecked (Lyrics)',
  'It Could Have Been Me - The Struts',
  'James Arthur - Impossible (Lyrics)',
  'Jim Croce - Time In A Bottle (Lyrics)',
  'John Newman - Love Me Again',
  'Jon Bellion - All Time Low (Official Music Video)',
  "Journey - Don't Stop Believin' (Lyrics)",
  "Kai - I'm So Sorry (Kung Fu Panda 3 vs Imagine Dra",
  'KALEO - Way Down We Go (Official Video)',
  "Kiss - I Was Made For Lovin' You",
  'Led Zeppelin - Immigrant Song | Lyrics',
  'Linkin Park - In The End',
  'Linkin Park - Numb (Wild Cards Remix)',
  "Livin' On A Prayer - Bon Jovi (Lyrics) 🎵",
  'Lost Frequencies & Calum Scott - Where Are You Now (Lyrics)',
  'Lukas Graham - 7 Years [Official Music Video]',
  'Maclemore & Ryan Lewis- Thrift Shop',
  'Manu Chao - Me Gustas Tu (Official Audio)',
  '"Martin Garrix, JVKE - Hero (Official Lyric Video)"',
  'Matthew Perryman Jones - Living in The Shadows (Unofficial Lyric Video)',
  'MEDUZA - Paradise (Lyrics) feat. Dermot Kennedy',
  'MEDUZA - Tell It To My Heart (Lyric Video) ft. Hozier',
  'Metallica - Nothing Else Matters',
  'MGMT - Little Dark Age (TikTok Remix) Lyrics | policemen swear to god loves seeping from the guns',
  'Michael Jackson - Billie Jean (Lyrics)',
  'Michael Jackson - Earth Song. (Lyrics).',
  "Michael Jackson - They Don't Care About Us (Lyric ",
  'Midi Culture - Little Something',
  'Mike Posner - I Took A Pill In Ibiza (SeeB Remix)',
  'Mild High Club - Homage',
  'Miyagi & Эндшпиль - In Love',
  'Mother Mother // Verbatim (LYRICS)',
  'Mr. Kitty - After Dark (Slowed Down)',
  'Muse - Supermassive Black Hole (Audio)',
  '"My Chemical Romance - Teenagers (Lyrics) ""Teenagers scare the livin sht outta me"" [Tiktok Song]"',
  'My Demons - Starset ',
  'Nathan Evans - Wellerman (Sea Shanty)',
  'New Divide (Official Video) - Linkin Park',
  'Nico & Vinz - Am I Wrong (Lyrics)',
  'Nirvana - Smells Like Teen Spirit (Official Music ',
  'Noah Kahan - False Confidence (Lyrics)',
  'OneRepublic - Counting Stars [Lyrics]',
  'OneRepublic - Run (Lyrics)',
  'OneRepublic - Someday (Lyrics)',
  '"OneRepublic, Mishaal Tamer, Assassin\'s Creed - Mirage (for Assassin\'s Creed Mirage) [Lyrics]"',
  'Panic! At The Disco – House of Memories [Lyrics]',
  'pink floyd - another brick in the wall',
  'Post Malone - Circles',
  'Post Malone - rockstar ft. 21 Savage',
  'Prayer In C (Lyrics) - Lilly Wood & The Prick',
  'pumped up kicks // foster the people - lyrics',
  'Queen - Another One Bites The Dust [Lyrics]',
  "Queen - Don't Stop Me Now (Official Video)",
  'Queen – Bohemian Rhapsody (Official Video Remastered)',
  'Radiohead - Karma Police',
  'Rammstein - Armee Der Tristen',
  'Rammstein - Deutschland (Lyrics)',
  'Rammstein - Du Hast (Official Audio)',
  'Rammstein - Engel (Official Audio)',
  'Rammstein - Giftig - English and German lyrics',
  'Rammstein - Ich Will (Audio)',
  'Rammstein - Mein Herz Brennt (Audio)',
  'Rammstein - Mutter (Official Video)',
  'Rammstein - Rammlied',
  'Rammstein - Rosenrot (Official Video)',
  'Rammstein -Ohne Dich (HQ)',
  'Rammstein- Radio (Audio HQ)',
  'Rammstein-Zeit (lyrics)',
  'Requiem For A Dream - Kate Chruscicka - Electric Violinist  - Clint Mansell',
  'The Rains of Castamere / Lannister Song (LYRICS) HD',
  'Rezo Da Bavshvebi - Megobaro / რეზო და ბავშვები - მეგობარო (Official Video)',
  'Scorpions - Wind Of Change (Lyrics)',
  'Set fire to the rain (lyrics) - Adele [English - Spanish]',
  'Shingeki no Kyojin 4th Season Part 3 Ending 2 Full 『二千年... 若しくは... 二万年後の君へ・・・』 Linked Horizon',
  "Sick Puppies - You're Going Down (Official Video)",
  'Skillet - Comatose [HQ]',
  'Sonne - Rammstein',
  'Status Quo   In The Army Now   Lyrics HQ',
  'Stephen - Crossfire',
  'Stromae - Alors On Danse (Clip Officiel)',
  "Stromae - L'enfer (Paroles / Lyrics)",
  'Stromae - Papaoutai',
  'Stromae - Santé (Paroles / Lyrics)',
  'Stromae - Tous les Mêmes (Lyrics/Paroles)',
  'Survivor - Eye of the Tiger (Lyrics)',
  'System Of A Down - Chop Suey! (lyrics)',
  '"Tally Hall - The Bidding (Lyrics) ""I\'ve been sleeping in a cardboard box"" [TikTok Song]"',
  'Tears For Fears - Everybody Wants To Rule The World (Lyrics)',
  'The Animals - House of the Rising Sun (1964) HQ/Widescreen ♫ 58 YEARS AGO',
  'The Beatles -  Let It Be - Let It Be (STEREO REMASTERED)',
  '"The Beatles - Eleanor Rigby (From ""Yellow Submarine"")"',
  'The Cranberries - Zombie (Official Music Video)',
  'The Doors - People Are Strange',
  'The Godfather Theme Song',
  'The Killers - Somebody Told Me Lyrics (HQ)',
  "The Mammas & The Papas - California Dreamin' (Lyrics)",
  "The Monkees - I'm A Believer (Lyrics)",
  'The Neighbourhood - Sweater Weather (Lyrics)',
  'The Rare Occasions - Notion (Lyrics)',
  '"The Rolling Stones - Paint It, Black (Official Lyric Video)"',
  'The Score - Head Up (Official Lyric Video)',
  'The Score - Revolution (Official Audio)',
  'The Score - Unstoppable (Lyric Video)',
  'The Script - Hall Of Fame',
  'The Show Must Go On-Queen Lyrics (HD)',
  'The Strokes - Brooklyn Bridge to Chorus',
  'The Strokes - Last Nite (Official Audio)',
  'The Strokes - Ode To The Mets (Audio)',
  'The Strokes - The Adults Are Talking (Official Video)',
  'The Turtles - Happy Together (Lyrics)',
  'The Wellermen - Hoist The Colours (Official Audio) ft. @ebucs @BigBrev @ebucs',
  'The Witcher Soundtrack - Toss A Coin To Your Witch',
  'Theory of a Deadman - Bad Girlfriend [OFFICIAL VID',
  'Thousand Foot Krutch: Untraveled Road (Official Au',
  'Tiesto - The Business (Official Lyric Video)',
  'Tom Gregory - Rather Be You (Lyrics)',
  'Tom Gregory - River (lyrics)',
  'Tom Walker - Leave a Light On (Lyrics)',
  'Tom Walker - Something Beautiful (Lyrics) ft. Masked Wolf',
  'twenty one pilots - Chlorine (Official Video)',
  'Twenty One Pilots - Heathens (Slowed Version)',
  'twenty one pilots - Stressed Out ( Lyrics )',
  "VALHALLA CALLING by Miracle Of Sound (Assassin's Creed) (Viking/Nordic/ Dark Folk Music)",
  'Vance Joy - Riptide (Lyrics)',
  'Wallows - Remember When (Official Audio)',
  'Warriors (ft. Imagine Dragons) | Worlds 2014 - Lea',
  "What I've Done (Official Video) - Linkin Park",
  "Why Don't We - Fallin' (Lyrics)",
  'Woodkid - Guns for Hire (Lyrics) from the series Arcane League of Legends',
  'Woodkid - Iron (Official Video)',
  'Woodkid - Run Boy Run (Official HD Video)',
  'X Ambassadors - Renegades (Lyric Video)',
  'ნიაზ დიასამიძე & 33ა -  ნამი ველს / Niaz Diasamidze & 33A -  Nami Vels',
  'ნიაზ დიასამიძე & 33ა - დრო / Niaz Diasamidze & 33A - Dro',
  'ნიაზ დიასამიძე & 33ა - დრომალე / Niaz Diasamidze & 33a - Dromale',
  'ნიაზ დიასამიძე & 33ა - სდუმს ტყე (ცხელი ძაღლი) / Niaz Diasmdze & 33A - Sdums tke (Hot Dog)',
  'ნიაზ დიასამიძე & 33ა - შოთა / Niaz Diasamidze & 33A - Shota',
  'ნიაზ დისამიძე & 33ა - გალაქტიონი / Niaz DiasamiZe & 33A - Galaktioni',
  'Daft Punk - Veridis Quo (Official Audio)',
];

final dummyUserAudios = dummyAudioNames
    .map(
      (e) => Audio(
        id: e.hashCode.toString(),
        title: e,
        durationMs: 0, // Replace 0 with the actual duration in milliseconds
        path: '1234', // Replace '' with the actual path of the audio file
        localPath: '1234', // Replace '' with the actual local path of the audio file
        author: 'Artist', // Replace '' with the actual author of the audio
        sizeBytes: 100, // Replace 0 with the actual size of the audio file in bytes
        youtubeVideoId: '21', // Replace '' with the actual YouTube video ID if applicable
        spotifyId: '', // Replace '' with the actual Spotify ID if applicable
        thumbnailPath: '', // Replace '' with the actual path of the thumbnail image
        thumbnailUrl: '', // Replace '' with the actual URL of the thumbnail image
        localThumbnailPath: '', // Replace '' with the actual local path of the thumbnail image
        audioLike: null,
        createdAt: DateTime.now(), // Replace null with the actual AudioLike object if applicable
        hiddenUserAudio: null,
      ),
    )
    .toList();
