name: sonify_storage
description: storage daos for the sonify app
version: 1.0.0

environment:
  sdk: ^3.1.4

dependencies:
  path_provider: ^2.1.1
  sqflite: ^2.3.3
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
