name: isolate_downloader
description: Multiple File Downloader
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
