name: sonify_video_player
description: A video player
version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  video_player: ^2.7.0
  wakelock_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
