name: Build and upload Android & IOS

on:
  push:
    branches: ['main']

jobs:
  build-packages:
    name: IPA & APK Build
    runs-on: macos-latest  # Use latest macOS for newest Xcode/Swift
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - name: Create GoogleServices-Info.plist
        run: echo '${{ secrets.GOOGLE_SERVICES_PLIST }}' > ios/Runner/GoogleService-Info.plist

      - name: Create firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS_DART }}" > lib/firebase_options.dart

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.x'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.0'  # Use a specific stable version
          architecture: x64
          cache: true

      - name: Extract version from pubspec.yaml
        run: echo "VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')" >> $GITHUB_ENV

      - name: Install flutterfire cli
        run: dart pub global activate flutterfire_cli

      - name: Check Xcode and Swift versions
        run: |
          # List available Xcode versions
          ls -la /Applications/ | grep Xcode
          # Use the latest Xcode version available
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version
          swift --version
          # Show available iOS SDKs
          xcodebuild -showsdks | grep iOS

      - name: Clean iOS build cache
        working-directory: ios
        run: |
          rm -rf Pods/
          rm -rf .symlinks/
          rm -rf Flutter/Flutter.framework
          rm -rf Flutter/Flutter.podspec
          rm -f Podfile.lock

      - name: Get dependencies
        run: |
          flutter pub get
          # Show current Firebase versions for debugging
          flutter pub deps | grep firebase

      - name: Install pods with updated Firebase versions
        working-directory: ios
        run: |
          # Remove existing pods and lockfile
          rm -rf Pods/ Podfile.lock
          # Show pod repo info
          pod --version
          # Install with explicit dependency resolution
          pod install --repo-update --clean-install --verbose

      - name: build runner in root
        run: dart run build_runner build

      - name: build runner in packages/sonify_client
        working-directory: ./packages/sonify_client
        run: dart run build_runner build

      - name: build runner in packages/domain_data
        working-directory: ./packages/domain_data
        run: dart run build_runner build

      - name: List available iOS destinations
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -showdestinations -quiet
        continue-on-error: true

      - name: Configure Xcode for generic iOS device
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -destination "generic/platform=iOS" -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO clean

      - name: Build IPA
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=LOCAL_API_URL=${{ secrets.LOCAL_API_URL }} \
            --dart-define=REMOTE_API_URL=${{ secrets.REMOTE_API_URL }} \
            --dart-define=LOCAL_WS_URL=${{ secrets.LOCAL_WS_URL }} \
            --dart-define=REMOTE_WS_URL=${{ secrets.REMOTE_WS_URL }} \
            --dart-define=GOOGLE_AUTH_CLIENT_ID_IOS=${{ secrets.GOOGLE_AUTH_CLIENT_ID_IOS }} \
            --dart-define=GOOGLE_AUTH_CLIENT_ID_WEB=${{ secrets.GOOGLE_AUTH_CLIENT_ID_WEB }} \
            --dart-define=SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
        env:
          FLUTTER_IOS_DESTINATION: "generic/platform=iOS"
          SWIFT_VERSION: "5.0"
          ENABLE_BITCODE: "NO"

      - name: Create Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip IPA output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Build APK
        run: |
          flutter build apk --release \
            --dart-define=LOCAL_API_URL=${{ secrets.LOCAL_API_URL }} \
            --dart-define=REMOTE_API_URL=${{ secrets.REMOTE_API_URL }} \
            --dart-define=LOCAL_WS_URL=${{ secrets.LOCAL_WS_URL }} \
            --dart-define=REMOTE_WS_URL=${{ secrets.REMOTE_WS_URL }} \
            --dart-define=GOOGLE_AUTH_CLIENT_ID_IOS=${{ secrets.GOOGLE_AUTH_CLIENT_ID_IOS }} \
            --dart-define=GOOGLE_AUTH_CLIENT_ID_WEB=${{ secrets.GOOGLE_AUTH_CLIENT_ID_WEB }} \
            --dart-define=SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: ${{ env.VERSION }}
          overwrite: true
          asset_name: sonify-${{ env.VERSION }}.ipa
          body: 'iOS release version ${{ env.VERSION }}'

      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag: ${{ env.VERSION }}
          overwrite: true
          asset_name: sonify-${{ env.VERSION }}.apk
          body: 'Android release version ${{ env.VERSION }}'
